name: CI Build with Anomaly Detection

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Dummy Build
        run: python app/main.py

      - name: Detect Anomaly
        run: python scripts/anomaly_detector.py

      - name: Update Build Metrics
        if: always()
        run: python scripts/update_metrics.py
